// GENERATED by @edgedb/generate v0.5.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $Text = $.ScalarType<"std::str", string>;
const Text: $.scalarTypeWithConstructor<_std.$str, never> = $.makeType<$.scalarTypeWithConstructor<_std.$str, never>>(_.spec, "c7ff1164-2a4b-11ef-8c8c-19bef2b71dbe", _.syntax.literal);

export type $Unit = {
  "KG": $.$expr_Literal<$Unit>;
  "GR": $.$expr_Literal<$Unit>;
  "STUK": $.$expr_Literal<$Unit>;
  "FLES": $.$expr_Literal<$Unit>;
  "DOOS": $.$expr_Literal<$Unit>;
  "PAK": $.$expr_Literal<$Unit>;
} & $.EnumType<"default::Unit", ["KG", "GR", "STUK", "FLES", "DOOS", "PAK"]>;
const Unit: $Unit = $.makeType<$Unit>(_.spec, "c802f2c0-2a4b-11ef-8db5-11dca93db027", _.syntax.literal);

export type $ArtikelλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "eenheid": $.PropertyDesc<$Unit, $.Cardinality.AtMostOne, false, false, false, false>;
  "titel": $.PropertyDesc<$Text, $.Cardinality.AtMostOne, true, false, false, false>;
  "<artikel[is ArtikelItem]": $.LinkDesc<$ArtikelItem, $.Cardinality.Many, {}, false, false,  false, false>;
  "<artikel": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Artikel = $.ObjectType<"default::Artikel", $ArtikelλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {titel: {__element__: $Text, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Artikel = $.makeType<$Artikel>(_.spec, "c8030477-2a4b-11ef-b058-adc0c1a718cd", _.syntax.literal);

const Artikel: $.$expr_PathNode<$.TypeSet<$Artikel, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Artikel, $.Cardinality.Many), null);

export type $ArtikelItemλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "artikel": $.LinkDesc<$Artikel, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "hoeveelheid": $.PropertyDesc<_std.$int64, $.Cardinality.AtMostOne, false, false, false, false>;
  "user": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $ArtikelItem = $.ObjectType<"default::ArtikelItem", $ArtikelItemλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $ArtikelItem = $.makeType<$ArtikelItem>(_.spec, "c8049dd5-2a4b-11ef-9dcf-07bce9d2bd4f", _.syntax.literal);

const ArtikelItem: $.$expr_PathNode<$.TypeSet<$ArtikelItem, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($ArtikelItem, $.Cardinality.Many), null);



export { Text, Unit, $Artikel, Artikel, $ArtikelItem, ArtikelItem };

type __defaultExports = {
  "Text": typeof Text;
  "Unit": typeof Unit;
  "Artikel": typeof Artikel;
  "ArtikelItem": typeof ArtikelItem
};
const __defaultExports: __defaultExports = {
  "Text": Text,
  "Unit": Unit,
  "Artikel": Artikel,
  "ArtikelItem": ArtikelItem
};
export default __defaultExports;
